
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    component: taskmanager
spec:
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  serviceName: flink-taskmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flokkr/flink
        args:
        - taskmanager.sh
        - start-foreground
        env:
        - name: LAUNCHER_UPDATE
          value: "true"
        envFrom:
        - configMapRef:
            name: flink-config
        imagePullPolicy: IfNotPresent
