kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-provisioner
  template:
    metadata:
      labels:
        app: csi-provisioner
    spec:
      serviceAccount: csi-ozone
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--csi-address=/var/lib/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/
        - name: ozone-csi
          image: elek/ozone:dev
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config
          args:
           - ozone
           - csi
      volumes:
        - name: socket-dir
          emptyDir:
