
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ozone-s3g-tls
spec:
  secretName: ozone-s3g-tls
  duration: 2160h
  renewBefore: 360h
  organization:
  - ozone
  commonName: s3g
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - server auth
  - client auth
  dnsNames:
  - ozone-s3g-0.ozone-s3g
  issuerRef:
    name: ozone-ca-issuer
    kind: Issuer
    group: cert-manager.io
