
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-hiveserver2
spec:
  serviceName: hive-hiveserver2
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: hive
      component: hiveserver2
  template:
    metadata:
      labels:
        app: hive
        component: hiveserver2
    spec:
      containers:
      - name: hiveserver2
        image: elek/hive:3.1.2
        args:
        - hive
        - --service
        - hiveserver2
        envFrom:
        - configMapRef:
            name: hive-config
        - configMapRef:
            name: hdfs-config
        - configMapRef:
            name: yarn-config
        volumeMounts:
        - name: data
          mountPath: /data
        - name: hadoop
          mountPath: /opt/hadoop
      volumes:
      - name: data
        emptyDir: {}
      - name: hadoop
        emptyDir: {}
      initContainers:
      - name: copy-hadoop
        image: flokkr/hadoop:3.1.2
        args:
        - cp
        - -r
        - /opt/hadoop/*
        - /target/
        volumeMounts:
        - name: hadoop
          mountPath: target
