apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: yarn-resourcemanager
spec:
  serviceName: yarn-resourcemanager
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: yarn
        component: resourcemanager
    spec:
      containers:
        - name: yarn-resourcemanager
          image: flokkr/hadoop:3.1
          args:
            - yarn
            - resourcemanager
          envFrom:
            - configMapRef:
                name: yarn-config
            - configMapRef:
                name: config
          volumeMounts:
            - name: ozonelib
              mountPath: /opt/ozonelib
          env:
            - name: "HADOOP_CLASSPATH"
              value: "/opt/ozonelib/hadoop-ozone-filesystem-lib-legacy.jar"
            - name: "CORE-SITE.XML_fs.defaultFS"
              value: "o3fs://bucket1.vol1/"
            - name: "CORE-SITE.XML_fs.AbstractFileSystem.o3fs.impl"
              value: "org.apache.hadoop.fs.ozone.OzFs"
      volumes:
        - name: config
          configMap:
            name: yarn-config
        - name: "data"
          emptyDir: {}
        - name: ozonelib
          emptyDir: {}
      initContainers:
        - name: ozone-lib
          image: quay.io/ozonedev/ozone:93e5d959338
          args:
            - cp
            - /opt/hadoop/share/ozone/lib/*legacy*.jar
            - /opt/ozonelib/hadoop-ozone-filesystem-lib-legacy.jar
          volumeMounts:
            - name: ozonelib
              mountPath: /opt/ozonelib
