
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-datanode
spec:
  serviceName: hdfs-datanode
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hdfs
        component: datanode
    spec:
      containers:
      - name: hdfs-datanode
        image: flokkr/hadoop
        args:
        - hdfs
        - datanode
        env:
        - name: WAITFOR
          value: hdfs-namenode-0.hdfs-namenode:9820
        envFrom:
        - configMapRef:
            name: hdfs-config
      volumes:
      - name: config
        configMap:
          name: hdfs-config
      - name: data
        emptyDir: {}
