apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-operator
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - --config.file=/conf/prometheus.yaml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: prometheusconf
