{
 "title": "Ozone",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Key allocation #",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "om_metrics_num_key_allocate" }
   ]
  },
  {
   "title": "Key Allocation rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(om_metrics_num_key_allocate[1m])"
    }
   ]
  },
  {
   "title": "Key Allcation (failure)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(om_metrics_num_key_allocate_fails[1m])"
    }
   ]
  },
  {
   "title": "Ozone datandoes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scm_node_manager_healthy_nodes", "legendFormat": "Healthy nodes" },
    { "expr": "scm_node_manager_dead_nodes", "legendFormat": "Dead nodes" }
   ]
  },
  {
   "title": "Chunk write / second (cluster wide)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_container_metrics_num_write_chunk[1m]))"
    }
   ]
  },
  {
   "title": "Write chunk # (per node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(storage_container_metrics_num_write_chunk[1m])"
    }
   ]
  }
 ]
}